# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt
    #role_hierarchy:
        #ROLE_ADMINISTRADOR:       [ROLE_ESTRATEGICO,ROLE_TACTICO]
        #ROLE_ESTRATEGICO:       ROLE_TACTICO
        # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
                entity:
                    class: AppBundle:Usuario
                    property: nomusuario
    firewalls:
        login:
            anonymous: ~
            form_login:
                csrf_provider: security.csrf.token_manager
                login_path: login
                check_path: login_check
                #nomusuario_parameter: _username
                #password_parameter: _password
                default_target_path: control_redirect
            logout:
                path: logout
                invalidate_session: true
                target: login
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_administrador }
         - { path: ^/interesado, roles: [ROLE_interesado, ROLE_alumno]}
         - { path: ^/tutor, roles: ROLE_tutor }
         - { path: ^/alumno, roles: [ROLE_alumno, ROLE_secretaria ]}
         - { path: ^/secretaria, roles: ROLE_secretaria }
         - { path: ^/director, roles: ROLE_director }
        # - { path: ^/admin, roles: ROLE_ADMINISTRADOR }